version: '3.8'

services:
  mongo:
    container_name: mongo_container
    image: mongo
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    command: mongod --bind_ip_all --smallfiles
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    container_name: backend_container
    build:
      context: .
      dockerfile: ./backend/Dockerfile.backend
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    container_name: frontend_container
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
    depends_on:
      - backend
    networks:
      - app-network

  mongo-express:
    container_name: adminMongo_container
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - app-network

  loadbalancer:
    container_name: nginx_container
    image: nginx
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge