# Etapa de construcción
FROM node:14 AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --production

# Etapa de producción
FROM node:14-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY . .

EXPOSE 3000

CMD ["npm", "start"]